name: Deploy to Rental Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd public_html/Jyukul && git fetch origin main && git reset --hard origin/main && composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan optimize:clear && php artisan config:cache && php artisan route:cache && chmod -R 775 storage bootstrap/cache"
          echo "Deployment completed successfully!"
